### ISSUE TITLE
Documentation missing important information about the Active Directory Schema

### ISSUE THREAD

**Issue by MikeStephens-MS** [Microsoft/SCCMdocs#193]
Windows Hello for Business requires the 2016 schema.  This is accomplished two ways.  In key-trust, the schema is upgraded when you install the first Windows Server 2016 domain controller in the domain.  In Certificate-trust, the schema must be updated manually using the adprep.exe utility from the Windows Server 2016 media,

**Comment by robstackmsft** [comment]
@MikeStephens-MS Thanks for this feedback Mike.
To document this, I think we will need more information. If you have any links to anything pertinent, that would be really helpful. In particular, do you have any pointers to information about exactly which schema must be updated? We already have a concept of extending the schema in Configuration Manager (for a different reason), and I don't want to confuse customers. Thanks!

**Comment by arob98** [comment]
Given we haven't seen an update, I'm going to close this issue. As needed, we can reopen it.
